drop table if exists task;
drop type if exists task_status;

create type task_status as enum (
  'in-progress',
  'completed',
  'cancelled'
);

create table task (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null default ''::text,
  slug text not null,
  status text not null default 'in-progress'::text,
  due_date date default null,
  collaborators text not null default '[]'::text,
  project_id bigint not null references project(id) on delete cascade,
  constraint task_pkey primary key (id)
) TABLESPACE pg_default;