drop table if exists project;
drop type if exists project_status;

create type project_status as enum (
  'in-progress',
  'completed',
  'cancelled'
);

create table project (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null default 'first-project'::text,
  slug text not null,
  description text not null default ''::text,
  status text not null default 'in-progress'::text,
  collaborators text not null default '[]'::text,
  constraint project_pkey primary key (id)
) TABLESPACE pg_default;